ShopCourses/Models/Course.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ShopCourses.Models
{
    public class Course
    {
        public int CourseId { get; set; }
        public int CategoryId { get; set; }
        [Required(ErrorMessage = "Wprowadź tytuł kursu")]
        [StringLength(100)]
        public string TitleCourse { get; set; }
        [Required(ErrorMessage = "Wprowadź nazwe autora")]
        [StringLength(100)]
        public string AuthorCourse { get; set; }
        public DateTime DateAdded { get; set; }
        [StringLength(100)]
        public string NamePicture { get; set; }
        public string DescriptionCourse { get; set; }
        public decimal PriceCourse { get; set; }
        public bool Bestseller { get; set; }
        public bool Hidden { get; set; }
        public string ShortenedDescription { get; set; }

        public virtual Category Category { get; set; }
    }
}

ShopCourses/Controllers/CourseController.cs
using ShopCourses.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopCourses.Controllers
{
    public class CourseController : Controller
    {
        private CourseContext db = new CourseContext();

        // GET: Course
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List(string nameCategory, string searchQuery = null)
        {
            var category = db.Categories.Include("Courses").Where(k => k.NameCategory.ToUpper() == nameCategory.ToUpper()).Single();
            var courses = category.Courses.Where(c => (searchQuery == null ||
            c.AuthorCourse.ToLower().Contains(searchQuery.ToLower()) ||
            c.TitleCourse.ToLower().Contains(searchQuery.ToLower())) && !c.Hidden);

            if (Request.IsAjaxRequest())
            {
                return PartialView("_CoursesList", courses);
            }

            return View(courses);
        }

        public ActionResult Details(int id)
        {
            var course = db.Courses.Find(id);

            return View(course);
        }

        [ChildActionOnly]
        [OutputCache(Duration = 60000)]
        public ActionResult MenuCategory()
        {
            var categories = db.Categories.ToList();

            return PartialView("_MenuCategory", categories);
        }

        public ActionResult CoursesTips(string term)
        {
            var courses = db.Courses
                .Where(c => !c.Hidden && c.TitleCourse.ToLower().Contains(term.ToLower()))
                .Take(5)
                .Select(s => new { label = s.TitleCourse });

            return Json(courses, JsonRequestBehavior.AllowGet);
        }

    }
}

ShopCourses/Views/Course/Details.cshtml
@model ShopCourses.Models.Course
@using ShopCourses.Infrastructure

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="ListaKategoriZawartosc">
    @Html.Action("MenuCategory")
    <div id="KategorieListPrawaSekcja">
        <div id="Breadcrumb">
            <img src="../Content/Images/dommaly.png" />
            <a href="link">
                @Html.MvcSiteMap().SiteMapPath()
            </a>
        </div>
        <section id="SekcjaKurs">
            <div id="KursLewa">
                <img src="@Url.PathToImages(Model.NamePicture)" />
            </div>
            <div id="KursPrawa">
                <div id="KursNazwa">
                    <h1>
                        @Model.TitleCourse
                    </h1>
                    <h2>
                        @Model.AuthorCourse
                    </h2>
                </div>
                <div id="KursCena">
                    <div>
                        @string.Format("{0:0.##}", Model.PriceCourse)<span>PLN</span>
                    </div>
                    <a href="@Url.Action("AddToBasket","Basket", new { id = Model.CourseId})"></a>
                </div>
                <div id="KursOpis">
                    @Model.DescriptionCourse
                </div>
                <div id="KursInfo">
                    @Model.ShortenedDescription
                </div>
                @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                {
                    <a href="@Url.Action("AddCourse", "Manage", new { courseId = Model.CourseId})" style="margin-top: 20px; font-weight: bold; display: block;">Edytuj</a>
                }
            </div>
        </section>
    </div>
</div>

ShopCourses/Views/Course/List.cshtml
@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div id="ListaKategoriZawartosc">
    @Html.Action("MenuCategory")

    <div id="KategorieListPrawaSekcja">
        <div id="Breadcrumb">
            <img src="../Content/Images/dommaly.png" />
            <a href="link">
                @Html.MvcSiteMap().SiteMapPath()
            </a>

            <form id="search-form" method="get" data-ajax="true" data-ajax-target="#SekcjaListaKategori">
                <input id="search-filter" type="search" name="searchQuery"
                       data-autocomplete-source="@Url.Action("CoursesTips")"
                       placeholder="Wprowadź tekst, aby wyfiltrować..." />
                <input type="submit" value="" />
            </form>

        </div>

            @Html.Partial("_CoursesList")
        
    </div>
</div>

@section Scripts
{
    @System.Web.Optimization.Scripts.Render("~/bundles/jqueryAndJqueryUI")

    <script>
        $(function () {
            var setupAutoComplete = function () {
                var $input = $(this);

                var options =
                    {
                        source: $input.attr("data-autocomplete-source"),
                        select: function (event, ui) {
                            $input = $(this);
                            $input.val(ui.item.label);
                            var $form = $input.parents("form:first");
                            $form.submit();
                        }
                    };

                $input.autocomplete(options);
            };

            var ajaxSubmit = function () {

                var $form = $(this);

                var settings = {
                    data: $(this).serialize(),
                    url: $(this).attr("action"),
                    type: $(this).attr("method")
                };

                $.ajax(settings).done(function (result) {
                    var $targetElement = $($form.data("ajax-target"));
                    var $newContent = $(result);
                    $($targetElement).replaceWith($newContent);
                    $newContent.effect("slide");
                });

                return false;
            };

            $("#search-filter").each(setupAutoComplete);
            $("#search-form").submit(ajaxSubmit);
        });
    </script>
}

ShopCourses/Views/Course/_CoursesList.cshtml
@model IEnumerable<ShopCourses.Models.Course>
    @using ShopCourses.Infrastructure

<div id="SekcjaListaKategori">
    <ul class="KursyTrzyKolumny MalaListaKategorii">
        @foreach (var course in Model)
        {
            <li>
                <article>
                    <a class="dodajDoKoszykaLink" href="@Url.Action("AddToBasket","Basket",new { id=course.CourseId})">
                        <img src="../Content/Images/koszyk.png" />
                    </a>
                    @if (course.Bestseller)
                    {
                        <div class="bestsellerFlag"></div>
                    }
                    <a class="kursSzczegolyLink" href="@Url.Action("Details","Course", new { id = course.CourseId})">
                        <img class="kurs" src="@Url.PathToImages(course.NamePicture)" />
                        <h1>
                            @course.AuthorCourse - @course.TitleCourse
                        </h1>
                    </a>
                </article>
            </li>
        }
    </ul>
</div>

ShopCourses/Views/Course/_MenuCategory.cshtml
@model IEnumerable<ShopCourses.Models.Category>
    @using ShopCourses.Infrastructure

<nav class="KategorieVertical">
    <ul>
        @foreach (var category in Model)
        {
            <li>
                <a href="@Url.Action("List", "Course", new { nameCategory = category.NameCategory.ToString() })" 
                   style="background-image: url(@Url.PathToIconsCategory(category.NameFileIcon)); ">
                    @category.NameCategory
                </a>
            </li>
        }
    </ul>
</nav>